### ISSUE TITLE
Always crash when tapping setting button

### ISSUE THREAD

**Issue by sr093906** [yanus171/Flym#100]
The app just crash when I tap the setting button. I have tried latest version. My phone is Huawei Nexus 6P on Android 8.1

**Comment by yanus171** [comment]
So send me a /storage/feedex/crash.txt

**Comment by sr093906** [comment]
> So send me a /storage/feedex/crash.txt

UNCAUGHT EXCEPTION
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.yanus171.feedexfork/ru.yanus171.feedexfork.activity.GeneralPrefsActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class fragment
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
at android.preference.ListPreference.getEntry(ListPreference.java:220)
at ru.yanus171.feedexfork.view.AutoSummaryListPreference.GetSummary(AutoSummaryListPreference.java:40)
at ru.yanus171.feedexfork.view.AutoSummaryListPreference.onSetInitialValue(AutoSummaryListPreference.java:46)
at android.preference.Preference.dispatchSetInitialValue(Preference.java:1557)
at android.preference.Preference.onAttachedToHierarchy(Preference.java:1328)
at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:163)
at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:105)
at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:101)
at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
at android.preference.GenericInflater.inflate(GenericInflater.java:327)
at android.preference.GenericInflater.inflate(GenericInflater.java:264)
at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:324)
at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:326)
at ru.yanus171.feedexfork.fragment.GeneralPrefsFragment.onCreate(GeneralPrefsFragment.java:82)
at android.app.Fragment.performCreate(Fragment.java:2489)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1237)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1462)
at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1704)
at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3537)
at android.app.FragmentController.onCreateView(FragmentController.java:98)
at android.app.Activity.onCreateView(Activity.java:6219)
at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:34)
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at ru.yanus171.feedexfork.activity.GeneralPrefsActivity.onCreate(GeneralPrefsActivity.java:63)
at android.app.Activity.performCreate(Activity.java:7009)
at android.app.Activity.performCreate(Activity.java:7000)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Version : 0.7.47
Version Code: 145
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Nexus 6P
Android Version : 8.1.0
User : android-build

**Comment by yanus171** [comment]
See if it is fixed https://github.com/yanus171/Flym/releases/tag/v0.7.52
