### ISSUE TITLE
Still Crash each time when scrolling down setting area

### ISSUE THREAD

**Issue by sr093906** [yanus171/Flym#108]
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
	at android.preference.ListPreference.getEntry(ListPreference.java:220)
	at android.preference.ListPreference.getSummary(ListPreference.java:165)
	at android.preference.Preference.onBindView(Preference.java:625)
	at android.preference.Preference.getView(Preference.java:559)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
	at android.widget.AbsListView.obtainView(AbsListView.java:2365)
	at android.widget.ListView.makeAndAddView(ListView.java:2052)
	at android.widget.ListView.fillDown(ListView.java:786)
	at android.widget.ListView.fillGap(ListView.java:750)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5225)
	at android.widget.ListView.trackMotionScroll(ListView.java:1971)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4769)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------------
Version : 0.7.52
Version Code: 150
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Nexus 6P
Android Version : 8.1.0
User : android-build

**Comment by yanus171** [comment]
Try it https://github.com/yanus171/Flym/releases/tag/v0.7.53

**Comment by sr093906** [comment]
It works. Thank you.
