### ISSUE TITLE
Crash when article have video

### ISSUE THREAD

**Issue by Dreamer-4pda** [yanus171/Flym#40]
time: 1546575598109
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:603)
	at org.chromium.android_webview.DefaultVideoPosterRequestHandler$$Lambda$0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6739)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by yanus171** [comment]
Give an url of the web page please

**Comment by yanus171** [comment]
Попробуйте последний релиз
Try the latest release 
(0.7.34)

**Comment by Dreamer-4pda** [comment]
Вроде бы не падает.
Посмотрю ещё несколько дней.

**Comment by yanus171** [comment]
Если все нормально, закройте исью

**Comment by Dreamer-4pda** [comment]
Да, все ок, больше не падает.
Спасибо!
