### ISSUE TITLE
App crashes when selecting text in article

### ISSUE THREAD

**Issue by DaleBCooper** [yanus171/Flym#78]
When I try to select text in an article the app crashes instantly after long pressing on text.

It does not crash after clearing the cache in app settings until the next restart. After a restart it crashes again as soon as I long press on some text.

-------------------
Stacktrace:
android.content.res.Resources$NotFoundException: Resource ID #0x20b0020
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
	at android.content.res.Resources.getInteger(Resources.java:1083)
	at org.chromium.ui.base.DeviceFormFactor.a(SourceFile:8)
	at org.chromium.content.browser.selection.SelectionPopupControllerImpl.a(SourceFile:210)
	at axr.onCreateActionMode(SourceFile:15)
	at ciN.onCreateActionMode(SourceFile:6)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2450)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:895)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:851)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:923)
	at android.view.View.startActionMode(View.java:6493)
	at cfS.a(SourceFile:1)
	at org.chromium.content.browser.selection.SelectionPopupControllerImpl.g(SourceFile:127)
	at cjP.a(SourceFile:31)
	at cjk.a(SourceFile:14)
	at aDI.run(Unknown Source:7)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6543)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by DaleBCooper** [comment]
Forgot to mention it happens on Android 8.1
Installed latest version from f-droid.

**Comment by yanus171** [comment]
Try to change the webview in developer settings (if you can) try to update Chrome

**Comment by DaleBCooper** [comment]
I have the latest version of Chrome running. The phone uses Chrome as webview implementation. Changing it in developer settings would require to disable Chrome. But this would result in the same version of webview anyways.
I cannot reproduce this error with other apps using webview.

**Comment by yanus171** [comment]
Can you try if this bug exists on app version https://github.com/yanus171/Flym/releases/tag/0.7.29

**Comment by DaleBCooper** [comment]
The bug exists in this version, too.

Interesting is: it does not happen all the time. After startup it crashes when long pressing on a word in article view. After the crash and automatic restart when I go to the settings menu and back to the article (without changing anything), the context menu appears and the app does not crash.
No idea what this means, but it seems 100% reproducible.

Could it be related to some apps I have installed because they appear in the context menu besides web search? There are:

Translate (Google translate)
Encrypt (open keychain)
Search Wikipedia (Wikipedia app)

**Comment by DaleBCooper** [comment]
![screenshot_20190221-200702](https://user-images.githubusercontent.com/9580059/53196046-4f0e5d80-3617-11e9-8f69-6e1ee9971f51.png)

**Comment by DaleBCooper** [comment]
The issue seems to be fixed with latest version, so I will close it.
