### ISSUE TITLE
Got some Stacktrace error

### ISSUE THREAD

**Issue by kowith337** [yanus171/Flym#91]
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void ru.yanus171.feedexfork.view.StatusText$FetcherObservable.ClearError()' on a null object reference
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:210)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:209)
	at android.os.HandlerThread.run(HandlerThread.java:61)

-------------------
Version : 0.7.40
Version Code: 138
Package : ru.yanus171.feedexfork
FilePath : /data/data/ru.yanus171.feedexfork/files
Phone Model: HTC One E9PLUS dual sim
Android Version : 5.0.2
User : buildteam
Total Internal memory : 24577437696
Available Internal memory : 6132498432
-------------------

```

Once I got this error above, I cannot fetch all feeds manually, close the app (by swipe out of recent) or force stop and reopen is the only way to fix, but it will get the same error above later next time.

**Comment by yanus171** [comment]
Install this version 
https://drive.google.com/file/d/1gwTbBMMfbKc-g90fYC0kr347nuiCrl-b/view?usp=drivesdk
С уважением, Алексей

Kowith Singkornkeeree <notifications@github.com> 13 марта 2019 г. 7:01:24 
написал:

**Comment by kowith337** [comment]
Sorry, I've installed from F-Droid, so maybe I need to backup, uninstall and reinstall to confirm fixed.
