### ISSUE TITLE
 out of memory crashes on every feed update

### ISSUE THREAD

**Issue by amit3s** [yanus171/Flym#949]
**Describe the bug**
From the last few days - I'm getting the crashes payed below. 

I use the app from fdroid store. That hasn't been updated since Jan this year, so it's not related to an app update. 

I recently got the android 15 update on the phone, maybe that is related? Can't say anything else has changed, this is a sudden new crash, but happens on every update now, and keeps happening all the time, making the app unusable, as it kept looping in the update feeds->crash cycle.

**Additional context**
Two recent crashes posted below.

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 577536 free bytes and 564KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.os.Parcel.readBundle(Parcel.java:3545)
	at android.os.Parcel.readBundle(Parcel.java:3528)
	at android.os.Message.readFromParcel(Message.java:663)
	at android.os.Message.-$$Nest$mreadFromParcel(Unknown Source:0)
	at android.os.Message$1.createFromParcel(Message.java:615)
	at android.os.Message$1.createFromParcel(Message.java:612)
	at android.os.Parcel.readTypedObject(Parcel.java:4218)
	at android.os.IMessenger$Stub.onTransact(IMessenger.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1505)
	at android.os.Binder.execTransact(Binder.java:1444)

-------------------
Version : 0.19.15
Version Code: 325
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Pixel 6a
Android Version : 15
Board : bluejay
Brand : google
Device : bluejay
Model : Pixel 6a
Product : bluejay
User : android-build
Total Internal memory : 118396899328
Available Internal memory : 35965198336
-------------------

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 883696 free bytes and 862KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at okio.Segment.<init>(Segment.kt:61)
	at okio.SegmentPool.take(SegmentPool.kt:88)
	at okio.Buffer.writableSegment$okio(Buffer.kt:1444)
	at okio.InputStreamSource.read(JvmOkio.kt:92)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
	at okhttp3.internal.http2.Http2Stream$FramingSource.receive$okhttp(Http2Stream.kt:445)
	at okhttp3.internal.http2.Http2Stream.receiveData(Http2Stream.kt:276)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.data(Http2Connection.kt:650)
	at okhttp3.internal.http2.Http2Reader.readData(Http2Reader.kt:180)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:119)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

-------------------
Version : 0.19.15
Version Code: 325
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Pixel 6a
Android Version : 15
Board : bluejay
Brand : google
Device : bluejay
Model : Pixel 6a
Product : bluejay
User : android-build
Total Internal memory : 118396899328
Available Internal memory : 50992189440
-------------------

**Comment by amit3s** [comment]
This still happens on 0.19.21. Happens on every feed refresh when loading full article text for offline use. Always runs out of memory and results in a crash.
